### ISSUE TITLE
Vodafone token payment

### ISSUE THREAD

**Issue by samtoya** [ovac/laravel-hubtel-payment#12]
1. Is there a way to send the Vodafone token with the request using the HubtelPayment facade?
2. Also how to check  Hubtel payment status?

**Comment by ovac** [comment]
Were you able to figure this out?  Sorry about the late response.

**Comment by samtoya** [comment]
Yes... I figured out the first one but I realized you didn't include checking the transaction status.

**Comment by ovac** [comment]
Oh! that's correct. I did not include checking the status. I assume this should be done in your Controller. Also, because  of the different use cases, I thought I'll let developers have some fun 🤪

**Comment by samtoya** [comment]
OK! If that's the case, no biggy! Thanks.
