### ISSUE TITLE
OVAC \ HubtelPayment \ Exception \ MissingParameterException (400) Validation Errors PrimaryCallbackUrl

### ISSUE THREAD

**Issue by nanadjei** [ovac/laravel-hubtel-payment#13]
I just copied your code for sending money and filled the details in yours with mine. But I keep on getting this error OVAC \ HubtelPayment \ Exception \ MissingParameterException (400)
Validation Errors PrimaryCallbackUrl`. I am working locally.

**Comment by ovac** [comment]
Have you been able to figure this out?

**Comment by ovac** [comment]
Be sure that you are passing in all the required parameters. 
You can check out the required parameters on the Hubtel API Documentation.

**Comment by nanadjei** [comment]
I think the issue because I was working locally. So my callback url was localhost and it needed an https.
